apiVersion: v1
kind: Secret
metadata:
  name: notizen-db-secret
  namespace: YOUR_NAMESPACE
type: Opaque
data:
  # echo -n "wert" | base64
  POSTGRES_DB:       YXBwZGI=
  POSTGRES_USER:     YXBwdXNlcg==
  POSTGRES_PASSWORD: YXBwcGFzc3dvcmQ=
