# PostgreSQL
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel9/postgresql-15:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/pgsql/data
        resources:
          requests:
            cpu: "10m"
            memory: "200Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# Frontend
kind: Deployment
apiVersion: apps/v1
metadata:
  name: html-openshift-app-light
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-openshift-app-light
  template:
    metadata:
      labels:
        app: html-openshift-app-light
    spec:
      containers:
      - name: html-openshift-app-light
        image: ghcr.io/pall-d-luca/html-openshift-postgresql-database:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        resources:
          requests:
            cpu: "10m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"