kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: html-openshift-app-database-hpa
  labels:
    app: html-openshift-app-database
    app.kubernetes.io/part-of: html-openshift-app-database
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: html-openshift-app-database
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70