kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: html-openshift-app-light-hpa
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: html-openshift-app-light
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60