kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi