apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: space-shooter-pvc             # z.B. myapp-pvc
  namespace: 264439-zli-lpallagi      # z.B. 264439-zli-lpallagi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi      # z.B. 1Gi, 2Gi, 5Gi
