kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: html-openshift-app-light
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
spec:
  to:
    kind: Service
    name: html-openshift-app-light
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect