kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  labels:
    app: html-openshift-app-light
    app.kubernetes.io/part-of: html-openshift-app-light
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: securepassword123
  POSTGRES_DB: appdb