apiVersion: v1
kind: Secret
metadata:
  name: space-shooter-db-secret       # z.B. myapp-db-secret
  namespace: 264439-zli-lpallagi           # z.B. 264439-zli-lpallagi
type: Opaque
stringData:
  POSTGRES_DB: appdb             # z.B. appdb         Kann man aussuchen
  POSTGRES_USER: appuser         # z.B. appuser       Kann man aussuchen
  POSTGRES_PASSWORD: apppassword # z.B. apppassword   Kann man aussuchen
